server:
  port: 8081


security:
  oauth2:
    client:
      client-id: infinity
      client-secret: 1234567890
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      user-info-uri: http://localhost:8080/oauth/user


